import type {
  Alumni,
  AttendanceRecord,
  Course,
  EnrollmentApplication,
  GradeEntry,
  Invoice,
  Lead,
  LiveSession,
  Student,
} from "./types";

export const students: Student[] = [
  {
    id: "STU-1042",
    name: "Maya Chen",
    email: "maya.chen@student.class365.edu",
    grade: "11",
    program: "STEM Honors",
    status: "active",
    gpa: 3.92,
    attendanceRate: 98,
    advisor: "Dr. Hale",
    enrolledAt: "2023-08-14",
    avatar: "MC",
  },
  {
    id: "STU-1098",
    name: "Jordan Blake",
    email: "jordan.blake@student.class365.edu",
    grade: "10",
    program: "Arts & Media",
    status: "active",
    gpa: 3.45,
    attendanceRate: 94,
    advisor: "Ms. Ortiz",
    enrolledAt: "2024-08-12",
    avatar: "JB",
  },
  {
    id: "STU-1120",
    name: "Aisha Rahman",
    email: "aisha.rahman@student.class365.edu",
    grade: "12",
    program: "International Baccalaureate",
    status: "active",
    gpa: 3.88,
    attendanceRate: 97,
    advisor: "Dr. Hale",
    enrolledAt: "2022-08-15",
    avatar: "AR",
  },
  {
    id: "STU-1155",
    name: "Leo Park",
    email: "leo.park@student.class365.edu",
    grade: "9",
    program: "General Studies",
    status: "pending",
    gpa: 0,
    attendanceRate: 0,
    advisor: "Mr. Singh",
    enrolledAt: "2026-07-01",
    avatar: "LP",
  },
  {
    id: "STU-0988",
    name: "Sofia Alvarez",
    email: "sofia.alvarez@alumni.class365.edu",
    grade: "Alumni",
    program: "Business Pathway",
    status: "alumni",
    gpa: 3.71,
    attendanceRate: 96,
    advisor: "Ms. Ortiz",
    enrolledAt: "2019-08-20",
    avatar: "SA",
  },
  {
    id: "STU-1201",
    name: "Noah Williams",
    email: "noah.williams@student.class365.edu",
    grade: "11",
    program: "STEM Honors",
    status: "active",
    gpa: 3.21,
    attendanceRate: 89,
    advisor: "Dr. Hale",
    enrolledAt: "2023-08-14",
    avatar: "NW",
  },
];

export const courses: Course[] = [
  {
    id: "CRS-301",
    code: "BIO-301",
    title: "Molecular Biology",
    teacher: "Dr. Elena Hale",
    students: 28,
    schedule: "Mon/Wed 09:00",
    mode: "hybrid",
    progress: 72,
    term: "Spring 2026",
  },
  {
    id: "CRS-220",
    code: "ENG-220",
    title: "World Literature",
    teacher: "Ms. Camila Ortiz",
    students: 32,
    schedule: "Tue/Thu 11:00",
    mode: "in-person",
    progress: 64,
    term: "Spring 2026",
  },
  {
    id: "CRS-410",
    code: "CSC-410",
    title: "Data Structures",
    teacher: "Mr. Raj Singh",
    students: 24,
    schedule: "Mon/Fri 13:30",
    mode: "online",
    progress: 81,
    term: "Spring 2026",
  },
  {
    id: "CRS-180",
    code: "ART-180",
    title: "Digital Studio",
    teacher: "Ms. Camila Ortiz",
    students: 18,
    schedule: "Wed 14:00",
    mode: "hybrid",
    progress: 58,
    term: "Spring 2026",
  },
  {
    id: "CRS-250",
    code: "HIS-250",
    title: "Modern World History",
    teacher: "Dr. Elena Hale",
    students: 30,
    schedule: "Tue/Thu 09:00",
    mode: "in-person",
    progress: 69,
    term: "Spring 2026",
  },
];

export const attendance: AttendanceRecord[] = [
  {
    id: "ATT-1",
    studentName: "Maya Chen",
    course: "BIO-301",
    date: "2026-07-13",
    status: "present",
    method: "auto",
  },
  {
    id: "ATT-2",
    studentName: "Jordan Blake",
    course: "ENG-220",
    date: "2026-07-13",
    status: "late",
    method: "biometric",
  },
  {
    id: "ATT-3",
    studentName: "Noah Williams",
    course: "CSC-410",
    date: "2026-07-13",
    status: "absent",
    method: "auto",
  },
  {
    id: "ATT-4",
    studentName: "Aisha Rahman",
    course: "HIS-250",
    date: "2026-07-13",
    status: "present",
    method: "auto",
  },
  {
    id: "ATT-5",
    studentName: "Leo Park",
    course: "ART-180",
    date: "2026-07-12",
    status: "excused",
    method: "manual",
  },
  {
    id: "ATT-6",
    studentName: "Maya Chen",
    course: "CSC-410",
    date: "2026-07-12",
    status: "present",
    method: "auto",
  },
];

export const grades: GradeEntry[] = [
  {
    id: "GRD-1",
    studentName: "Maya Chen",
    course: "BIO-301",
    assignment: "Lab Report 4",
    score: 96,
    maxScore: 100,
    weight: "15%",
    submittedAt: "2026-07-10",
  },
  {
    id: "GRD-2",
    studentName: "Aisha Rahman",
    course: "HIS-250",
    assignment: "Essay: Decolonization",
    score: 91,
    maxScore: 100,
    weight: "20%",
    submittedAt: "2026-07-09",
  },
  {
    id: "GRD-3",
    studentName: "Jordan Blake",
    course: "ENG-220",
    assignment: "Reading Response 7",
    score: 84,
    maxScore: 100,
    weight: "10%",
    submittedAt: "2026-07-11",
  },
  {
    id: "GRD-4",
    studentName: "Noah Williams",
    course: "CSC-410",
    assignment: "Project Milestone 2",
    score: 78,
    maxScore: 100,
    weight: "25%",
    submittedAt: "2026-07-08",
  },
  {
    id: "GRD-5",
    studentName: "Maya Chen",
    course: "CSC-410",
    assignment: "Project Milestone 2",
    score: 94,
    maxScore: 100,
    weight: "25%",
    submittedAt: "2026-07-08",
  },
];

export const invoices: Invoice[] = [
  {
    id: "INV-8841",
    studentName: "Maya Chen",
    description: "Spring 2026 Tuition — Installment 3",
    amount: 2450,
    dueDate: "2026-07-20",
    status: "pending",
  },
  {
    id: "INV-8830",
    studentName: "Jordan Blake",
    description: "Arts Lab Fee",
    amount: 180,
    dueDate: "2026-07-05",
    status: "overdue",
  },
  {
    id: "INV-8822",
    studentName: "Aisha Rahman",
    description: "IB Exam Registration",
    amount: 420,
    dueDate: "2026-06-30",
    status: "paid",
  },
  {
    id: "INV-8850",
    studentName: "Leo Park",
    description: "Enrollment Deposit",
    amount: 500,
    dueDate: "2026-07-25",
    status: "draft",
  },
  {
    id: "INV-8811",
    studentName: "Noah Williams",
    description: "Spring 2026 Tuition — Installment 3",
    amount: 2450,
    dueDate: "2026-07-20",
    status: "pending",
  },
];

export const leads: Lead[] = [
  {
    id: "LEAD-220",
    name: "Priya Nair",
    email: "priya.nair@email.com",
    source: "Open House",
    stage: "tour",
    interest: "STEM Honors",
    lastContact: "2026-07-12",
    score: 86,
  },
  {
    id: "LEAD-221",
    name: "Ethan Cole",
    email: "ethan.cole@email.com",
    source: "Website",
    stage: "application",
    interest: "Arts & Media",
    lastContact: "2026-07-11",
    score: 74,
  },
  {
    id: "LEAD-222",
    name: "Amara Okonkwo",
    email: "amara.o@email.com",
    source: "Referral",
    stage: "accepted",
    interest: "International Baccalaureate",
    lastContact: "2026-07-10",
    score: 93,
  },
  {
    id: "LEAD-223",
    name: "Lucas Meyer",
    email: "lucas.meyer@email.com",
    source: "Social Ads",
    stage: "inquiry",
    interest: "General Studies",
    lastContact: "2026-07-13",
    score: 52,
  },
  {
    id: "LEAD-224",
    name: "Hannah Brooks",
    email: "hannah.b@email.com",
    source: "Counselor Fair",
    stage: "enrolled",
    interest: "Business Pathway",
    lastContact: "2026-07-08",
    score: 97,
  },
];

export const alumni: Alumni[] = [
  {
    id: "ALM-01",
    name: "Sofia Alvarez",
    graduationYear: 2023,
    program: "Business Pathway",
    employer: "Northline Capital",
    location: "Chicago, IL",
    engagement: "high",
    donated: 1200,
  },
  {
    id: "ALM-02",
    name: "Marcus Lee",
    graduationYear: 2021,
    program: "STEM Honors",
    employer: "Orbit Robotics",
    location: "Austin, TX",
    engagement: "medium",
    donated: 350,
  },
  {
    id: "ALM-03",
    name: "Elena Voss",
    graduationYear: 2020,
    program: "Arts & Media",
    employer: "Studio Frame",
    location: "Los Angeles, CA",
    engagement: "high",
    donated: 2500,
  },
  {
    id: "ALM-04",
    name: "David Kim",
    graduationYear: 2022,
    program: "International Baccalaureate",
    employer: "UN Youth Corps",
    location: "Geneva, CH",
    engagement: "low",
    donated: 0,
  },
];

export const liveSessions: LiveSession[] = [
  {
    id: "LIVE-1",
    title: "Enzyme Kinetics Workshop",
    course: "BIO-301",
    host: "Dr. Elena Hale",
    startsAt: "2026-07-14T10:00:00",
    duration: "45 min",
    attendees: 22,
    status: "live",
  },
  {
    id: "LIVE-2",
    title: "Graph Traversal Office Hours",
    course: "CSC-410",
    host: "Mr. Raj Singh",
    startsAt: "2026-07-14T15:30:00",
    duration: "60 min",
    attendees: 0,
    status: "upcoming",
  },
  {
    id: "LIVE-3",
    title: "Literary Salon: Magical Realism",
    course: "ENG-220",
    host: "Ms. Camila Ortiz",
    startsAt: "2026-07-13T11:00:00",
    duration: "50 min",
    attendees: 29,
    status: "ended",
  },
];

export const applications: EnrollmentApplication[] = [
  {
    id: "APP-771",
    applicant: "Priya Nair",
    program: "STEM Honors",
    grade: "9",
    submittedAt: "2026-07-09",
    status: "interview",
    completeness: 92,
  },
  {
    id: "APP-772",
    applicant: "Ethan Cole",
    program: "Arts & Media",
    grade: "10",
    submittedAt: "2026-07-08",
    status: "documents",
    completeness: 68,
  },
  {
    id: "APP-773",
    applicant: "Amara Okonkwo",
    program: "International Baccalaureate",
    grade: "11",
    submittedAt: "2026-07-05",
    status: "approved",
    completeness: 100,
  },
  {
    id: "APP-774",
    applicant: "Lucas Meyer",
    program: "General Studies",
    grade: "9",
    submittedAt: "2026-07-12",
    status: "review",
    completeness: 45,
  },
  {
    id: "APP-775",
    applicant: "Riley Zhao",
    program: "STEM Honors",
    grade: "10",
    submittedAt: "2026-07-11",
    status: "waitlist",
    completeness: 100,
  },
];

export const dashboardStats = {
  activeStudents: 1284,
  pendingEnrollments: 47,
  attendanceToday: 96.4,
  outstandingBilling: 128400,
  openLeads: 63,
  liveSessions: 4,
  avgGpa: 3.42,
  alumniEngaged: 312,
};

export const activityFeed = [
  {
    id: 1,
    text: "Amara Okonkwo accepted offer for IB program",
    time: "12 min ago",
    type: "crm",
  },
  {
    id: 2,
    text: "Auto-attendance synced for BIO-301 (28/28)",
    time: "28 min ago",
    type: "attendance",
  },
  {
    id: 3,
    text: "Invoice INV-8830 marked overdue — Jordan Blake",
    time: "1 hr ago",
    type: "billing",
  },
  {
    id: 4,
    text: "Maya Chen submitted Lab Report 4 — scored 96%",
    time: "2 hr ago",
    type: "gradebook",
  },
  {
    id: 5,
    text: "Distance session started: Enzyme Kinetics Workshop",
    time: "3 hr ago",
    type: "lms",
  },
];

export const reportHighlights = [
  {
    label: "Enrollment conversion",
    value: "34%",
    delta: "+4.2%",
    positive: true,
  },
  {
    label: "Average daily attendance",
    value: "95.8%",
    delta: "+1.1%",
    positive: true,
  },
  {
    label: "Tuition collection rate",
    value: "91%",
    delta: "-2.3%",
    positive: false,
  },
  {
    label: "Course completion (online)",
    value: "88%",
    delta: "+6.0%",
    positive: true,
  },
  {
    label: "Alumni event RSVP",
    value: "214",
    delta: "+38",
    positive: true,
  },
  {
    label: "CRM response time",
    value: "4.2h",
    delta: "-1.5h",
    positive: true,
  },
];
