import type {
  Alumni,
  AttendanceRecord,
  ClassPeriod,
  Course,
  ElectiveOffering,
  EnrollmentApplication,
  GradeEntry,
  HealthRecord,
  Integration,
  Invoice,
  Lead,
  LibraryItem,
  LiveSession,
  Message,
  SchoolBand,
  SocialPost,
  Student,
  StudentCourseEnrollment,
  YearLevel,
} from "./types";

export const YEAR_LEVELS: YearLevel[] = [
  "Kindy",
  "Year 1",
  "Year 2",
  "Year 3",
  "Year 4",
  "Year 5",
  "Year 6",
  "Year 7",
  "Year 8",
  "Year 9",
  "Year 10",
  "Year 11",
  "Year 12",
  "Year 13",
];

export const SCHOOL_BANDS: SchoolBand[] = [
  "Early Childhood",
  "Primary",
  "Intermediate",
  "Secondary",
];

export function bandForYear(year: YearLevel): SchoolBand {
  if (year === "Kindy") return "Early Childhood";
  if (
    year === "Year 1" ||
    year === "Year 2" ||
    year === "Year 3" ||
    year === "Year 4" ||
    year === "Year 5" ||
    year === "Year 6"
  ) {
    return "Primary";
  }
  if (year === "Year 7" || year === "Year 8") return "Intermediate";
  return "Secondary";
}

export const yearLevelCensus: { yearLevel: YearLevel; students: number }[] = [
  { yearLevel: "Kindy", students: 42 },
  { yearLevel: "Year 1", students: 58 },
  { yearLevel: "Year 2", students: 61 },
  { yearLevel: "Year 3", students: 64 },
  { yearLevel: "Year 4", students: 67 },
  { yearLevel: "Year 5", students: 70 },
  { yearLevel: "Year 6", students: 72 },
  { yearLevel: "Year 7", students: 88 },
  { yearLevel: "Year 8", students: 91 },
  { yearLevel: "Year 9", students: 104 },
  { yearLevel: "Year 10", students: 112 },
  { yearLevel: "Year 11", students: 118 },
  { yearLevel: "Year 12", students: 109 },
  { yearLevel: "Year 13", students: 98 },
];

export const students: Student[] = [
  {
    id: "STU-1042",
    name: "Maya Chen",
    email: "maya.chen@student.class365.edu",
    yearLevel: "Year 11",
    band: "Secondary",
    homeroom: "11-Hale",
    program: "NCEA STEM Pathway",
    status: "active",
    gpa: 3.92,
    attendanceRate: 98,
    advisor: "Dr. Hale",
    guardian: "Daniel Chen",
    guardianEmail: "parent@class365.edu",
    enrolledAt: "2023-02-01",
    avatar: "MC",
    creditsEarned: 48,
    creditsRequired: 80,
    electiveSlots: 3,
    electiveFilled: 2,
  },
  {
    id: "STU-1098",
    name: "Jordan Blake",
    email: "jordan.blake@student.class365.edu",
    yearLevel: "Year 8",
    band: "Intermediate",
    homeroom: "8-Ortiz",
    program: "Arts & Media",
    status: "active",
    gpa: 3.45,
    attendanceRate: 94,
    advisor: "Ms. Ortiz",
    guardian: "Sam Blake",
    guardianEmail: "sam.blake@email.com",
    enrolledAt: "2024-02-01",
    avatar: "JB",
    creditsEarned: 18,
    creditsRequired: 40,
    electiveSlots: 2,
    electiveFilled: 2,
  },
  {
    id: "STU-1120",
    name: "Aisha Rahman",
    email: "aisha.rahman@student.class365.edu",
    yearLevel: "Year 13",
    band: "Secondary",
    homeroom: "13-Hale",
    program: "NCEA Excellence / Scholarship",
    status: "active",
    gpa: 3.88,
    attendanceRate: 97,
    advisor: "Dr. Hale",
    guardian: "Farah Rahman",
    guardianEmail: "farah.r@email.com",
    enrolledAt: "2020-02-03",
    avatar: "AR",
    creditsEarned: 74,
    creditsRequired: 80,
    electiveSlots: 4,
    electiveFilled: 4,
  },
  {
    id: "STU-1155",
    name: "Leo Park",
    email: "leo.park@student.class365.edu",
    yearLevel: "Year 1",
    band: "Primary",
    homeroom: "1-Singh",
    program: "Junior Primary",
    status: "pending",
    gpa: 0,
    attendanceRate: 0,
    advisor: "Mr. Singh",
    guardian: "Hana Park",
    guardianEmail: "hana.park@email.com",
    enrolledAt: "2026-01-28",
    avatar: "LP",
    creditsEarned: 0,
    creditsRequired: 0,
    electiveSlots: 0,
    electiveFilled: 0,
  },
  {
    id: "STU-1001",
    name: "Tia Ngata",
    email: "tia.ngata@student.class365.edu",
    yearLevel: "Kindy",
    band: "Early Childhood",
    homeroom: "Kindy-A",
    program: "Early Learning",
    status: "active",
    gpa: 0,
    attendanceRate: 96,
    advisor: "Ms. Ortiz",
    guardian: "Wiremu Ngata",
    guardianEmail: "w.ngata@email.com",
    enrolledAt: "2025-02-03",
    avatar: "TN",
    creditsEarned: 0,
    creditsRequired: 0,
    electiveSlots: 0,
    electiveFilled: 0,
  },
  {
    id: "STU-0988",
    name: "Sofia Alvarez",
    email: "sofia.alvarez@alumni.class365.edu",
    yearLevel: "Year 13",
    band: "Secondary",
    homeroom: "Alumni",
    program: "Business Pathway",
    status: "alumni",
    gpa: 3.71,
    attendanceRate: 96,
    advisor: "Ms. Ortiz",
    guardian: "—",
    guardianEmail: "—",
    enrolledAt: "2019-02-04",
    avatar: "SA",
    creditsEarned: 80,
    creditsRequired: 80,
    electiveSlots: 4,
    electiveFilled: 4,
  },
  {
    id: "STU-1201",
    name: "Noah Williams",
    email: "noah.williams@student.class365.edu",
    yearLevel: "Year 10",
    band: "Secondary",
    homeroom: "10-Hale",
    program: "NCEA STEM Pathway",
    status: "active",
    gpa: 3.21,
    attendanceRate: 89,
    advisor: "Dr. Hale",
    guardian: "Priya Williams",
    guardianEmail: "priya.w@email.com",
    enrolledAt: "2023-02-01",
    avatar: "NW",
    creditsEarned: 32,
    creditsRequired: 80,
    electiveSlots: 2,
    electiveFilled: 1,
  },
  {
    id: "STU-1210",
    name: "Amelia Scott",
    email: "amelia.scott@student.class365.edu",
    yearLevel: "Year 5",
    band: "Primary",
    homeroom: "5-B",
    program: "Primary Core",
    status: "active",
    gpa: 0,
    attendanceRate: 95,
    advisor: "Ms. Ortiz",
    guardian: "James Scott",
    guardianEmail: "j.scott@email.com",
    enrolledAt: "2021-02-01",
    avatar: "AS",
    creditsEarned: 0,
    creditsRequired: 0,
    electiveSlots: 1,
    electiveFilled: 1,
  },
];

export const courses: Course[] = [
  {
    id: "CRS-K01",
    code: "ELC-K",
    title: "Kindy Discovery Play",
    teacher: "Ms. Camila Ortiz",
    yearLevels: ["Kindy"],
    band: "Early Childhood",
    students: 22,
    schedule: "Daily 09:00",
    mode: "in-person",
    progress: 55,
    term: "Term 2 2026",
    credits: 0,
    kind: "core",
    seats: 24,
  },
  {
    id: "CRS-105",
    code: "LIT-05",
    title: "Primary Literacy Circles",
    teacher: "Ms. Camila Ortiz",
    yearLevels: ["Year 4", "Year 5", "Year 6"],
    band: "Primary",
    students: 28,
    schedule: "Mon/Wed 09:00",
    mode: "in-person",
    progress: 68,
    term: "Term 2 2026",
    credits: 2,
    kind: "core",
    seats: 30,
  },
  {
    id: "CRS-208",
    code: "SCI-08",
    title: "Intermediate Science Lab",
    teacher: "Mr. Raj Singh",
    yearLevels: ["Year 7", "Year 8"],
    band: "Intermediate",
    students: 26,
    schedule: "Tue/Thu 11:00",
    mode: "hybrid",
    progress: 61,
    term: "Term 2 2026",
    credits: 3,
    kind: "core",
    seats: 28,
  },
  {
    id: "CRS-301",
    code: "BIO-11",
    title: "NCEA Biology",
    teacher: "Dr. Elena Hale",
    yearLevels: ["Year 11", "Year 12"],
    band: "Secondary",
    students: 28,
    schedule: "Mon/Wed 09:00",
    mode: "hybrid",
    progress: 72,
    term: "Term 2 2026",
    credits: 4,
    kind: "core",
    seats: 30,
  },
  {
    id: "CRS-410",
    code: "DIG-13",
    title: "Digital Technologies",
    teacher: "Mr. Raj Singh",
    yearLevels: ["Year 12", "Year 13"],
    band: "Secondary",
    students: 24,
    schedule: "Mon/Fri 13:30",
    mode: "online",
    progress: 81,
    term: "Term 2 2026",
    credits: 4,
    kind: "pathway",
    seats: 26,
  },
  {
    id: "CRS-220",
    code: "ENG-10",
    title: "English — World Texts",
    teacher: "Ms. Camila Ortiz",
    yearLevels: ["Year 10"],
    band: "Secondary",
    students: 32,
    schedule: "Tue/Thu 11:00",
    mode: "in-person",
    progress: 64,
    term: "Term 2 2026",
    credits: 4,
    kind: "core",
    seats: 34,
  },
  {
    id: "CRS-EL1",
    code: "MUS-09",
    title: "Contemporary Music Elective",
    teacher: "Ms. Camila Ortiz",
    yearLevels: ["Year 9", "Year 10"],
    band: "Secondary",
    students: 18,
    schedule: "Wed 14:00",
    mode: "in-person",
    progress: 50,
    term: "Term 2 2026",
    credits: 2,
    kind: "elective",
    seats: 20,
  },
  {
    id: "CRS-EL2",
    code: "ART-08",
    title: "Visual Arts Studio",
    teacher: "Ms. Camila Ortiz",
    yearLevels: ["Year 7", "Year 8"],
    band: "Intermediate",
    students: 20,
    schedule: "Fri 11:00",
    mode: "in-person",
    progress: 58,
    term: "Term 2 2026",
    credits: 2,
    kind: "elective",
    seats: 22,
  },
  {
    id: "CRS-EL3",
    code: "ROB-11",
    title: "Robotics Elective",
    teacher: "Mr. Raj Singh",
    yearLevels: ["Year 11", "Year 12"],
    band: "Secondary",
    students: 16,
    schedule: "Thu 13:30",
    mode: "hybrid",
    progress: 66,
    term: "Term 2 2026",
    credits: 3,
    kind: "elective",
    seats: 18,
  },
];

export const studentEnrollments: StudentCourseEnrollment[] = [
  {
    id: "ENR-01",
    studentId: "STU-1042",
    studentName: "Maya Chen",
    yearLevel: "Year 11",
    courseCode: "BIO-11",
    courseTitle: "NCEA Biology",
    kind: "core",
    credits: 4,
    status: "enrolled",
    term: "Term 2 2026",
    teacher: "Dr. Elena Hale",
  },
  {
    id: "ENR-02",
    studentId: "STU-1042",
    studentName: "Maya Chen",
    yearLevel: "Year 11",
    courseCode: "ROB-11",
    courseTitle: "Robotics Elective",
    kind: "elective",
    credits: 3,
    status: "enrolled",
    term: "Term 2 2026",
    teacher: "Mr. Raj Singh",
  },
  {
    id: "ENR-03",
    studentId: "STU-1201",
    studentName: "Noah Williams",
    yearLevel: "Year 10",
    courseCode: "ENG-10",
    courseTitle: "English — World Texts",
    kind: "core",
    credits: 4,
    status: "enrolled",
    term: "Term 2 2026",
    teacher: "Ms. Camila Ortiz",
  },
  {
    id: "ENR-04",
    studentId: "STU-1201",
    studentName: "Noah Williams",
    yearLevel: "Year 10",
    courseCode: "MUS-09",
    courseTitle: "Contemporary Music Elective",
    kind: "elective",
    credits: 2,
    status: "waitlist",
    term: "Term 2 2026",
    teacher: "Ms. Camila Ortiz",
  },
  {
    id: "ENR-05",
    studentId: "STU-1098",
    studentName: "Jordan Blake",
    yearLevel: "Year 8",
    courseCode: "SCI-08",
    courseTitle: "Intermediate Science Lab",
    kind: "core",
    credits: 3,
    status: "enrolled",
    term: "Term 2 2026",
    teacher: "Mr. Raj Singh",
  },
  {
    id: "ENR-06",
    studentId: "STU-1098",
    studentName: "Jordan Blake",
    yearLevel: "Year 8",
    courseCode: "ART-08",
    courseTitle: "Visual Arts Studio",
    kind: "elective",
    credits: 2,
    status: "enrolled",
    term: "Term 2 2026",
    teacher: "Ms. Camila Ortiz",
  },
  {
    id: "ENR-07",
    studentId: "STU-1120",
    studentName: "Aisha Rahman",
    yearLevel: "Year 13",
    courseCode: "DIG-13",
    courseTitle: "Digital Technologies",
    kind: "pathway",
    credits: 4,
    status: "enrolled",
    term: "Term 2 2026",
    teacher: "Mr. Raj Singh",
  },
  {
    id: "ENR-08",
    studentId: "STU-1120",
    studentName: "Aisha Rahman",
    yearLevel: "Year 13",
    courseCode: "BIO-11",
    courseTitle: "NCEA Biology",
    kind: "core",
    credits: 4,
    status: "completed",
    term: "Term 1 2026",
    teacher: "Dr. Elena Hale",
  },
  {
    id: "ENR-09",
    studentId: "STU-1210",
    studentName: "Amelia Scott",
    yearLevel: "Year 5",
    courseCode: "LIT-05",
    courseTitle: "Primary Literacy Circles",
    kind: "core",
    credits: 2,
    status: "enrolled",
    term: "Term 2 2026",
    teacher: "Ms. Camila Ortiz",
  },
];

export const electiveOfferings: ElectiveOffering[] = [
  {
    id: "ELC-01",
    code: "MUS-09",
    title: "Contemporary Music Elective",
    yearLevels: ["Year 9", "Year 10"],
    credits: 2,
    seats: 20,
    enrolled: 18,
    waitlist: 3,
    teacher: "Ms. Camila Ortiz",
    term: "Term 2 2026",
    category: "Arts",
  },
  {
    id: "ELC-02",
    code: "ART-08",
    title: "Visual Arts Studio",
    yearLevels: ["Year 7", "Year 8"],
    credits: 2,
    seats: 22,
    enrolled: 20,
    waitlist: 1,
    teacher: "Ms. Camila Ortiz",
    term: "Term 2 2026",
    category: "Arts",
  },
  {
    id: "ELC-03",
    code: "ROB-11",
    title: "Robotics Elective",
    yearLevels: ["Year 11", "Year 12"],
    credits: 3,
    seats: 18,
    enrolled: 16,
    waitlist: 2,
    teacher: "Mr. Raj Singh",
    term: "Term 2 2026",
    category: "STEM",
  },
  {
    id: "ELC-04",
    code: "BIS-05",
    title: "Bislama Enrichment",
    yearLevels: ["Year 4", "Year 5", "Year 6"],
    credits: 1,
    seats: 24,
    enrolled: 21,
    waitlist: 0,
    teacher: "Ms. Camila Ortiz",
    term: "Term 2 2026",
    category: "Languages",
  },
  {
    id: "ELC-05",
    code: "MED-12",
    title: "Media Production Elective",
    yearLevels: ["Year 12", "Year 13"],
    credits: 3,
    seats: 16,
    enrolled: 16,
    waitlist: 4,
    teacher: "Dr. Elena Hale",
    term: "Term 2 2026",
    category: "Media",
  },
];

export const attendance: AttendanceRecord[] = [
  {
    id: "ATT-1",
    studentName: "Maya Chen",
    yearLevel: "Year 11",
    course: "BIO-11",
    date: "2026-07-13",
    status: "present",
    method: "auto",
  },
  {
    id: "ATT-2",
    studentName: "Jordan Blake",
    yearLevel: "Year 8",
    course: "SCI-08",
    date: "2026-07-13",
    status: "late",
    method: "biometric",
  },
  {
    id: "ATT-3",
    studentName: "Noah Williams",
    yearLevel: "Year 10",
    course: "ENG-10",
    date: "2026-07-13",
    status: "absent",
    method: "auto",
  },
  {
    id: "ATT-4",
    studentName: "Aisha Rahman",
    yearLevel: "Year 13",
    course: "DIG-13",
    date: "2026-07-13",
    status: "present",
    method: "auto",
  },
  {
    id: "ATT-5",
    studentName: "Tia Ngata",
    yearLevel: "Kindy",
    course: "ELC-K",
    date: "2026-07-13",
    status: "present",
    method: "manual",
  },
  {
    id: "ATT-6",
    studentName: "Amelia Scott",
    yearLevel: "Year 5",
    course: "LIT-05",
    date: "2026-07-12",
    status: "excused",
    method: "manual",
  },
  {
    id: "ATT-7",
    studentName: "Leo Park",
    yearLevel: "Year 1",
    course: "Junior Roll",
    date: "2026-07-12",
    status: "present",
    method: "manual",
  },
];

export const grades: GradeEntry[] = [
  {
    id: "GRD-1",
    studentName: "Maya Chen",
    yearLevel: "Year 11",
    course: "BIO-11",
    assignment: "Internal Assessment 2.4",
    score: 96,
    maxScore: 100,
    weight: "15%",
    submittedAt: "2026-07-10",
    scale: "ncea",
  },
  {
    id: "GRD-2",
    studentName: "Aisha Rahman",
    yearLevel: "Year 13",
    course: "DIG-13",
    assignment: "Scholarship Portfolio Draft",
    score: 91,
    maxScore: 100,
    weight: "20%",
    submittedAt: "2026-07-09",
    scale: "ncea",
  },
  {
    id: "GRD-3",
    studentName: "Jordan Blake",
    yearLevel: "Year 8",
    course: "SCI-08",
    assignment: "Lab Journal 4",
    score: 84,
    maxScore: 100,
    weight: "10%",
    submittedAt: "2026-07-11",
    scale: "numeric",
  },
  {
    id: "GRD-4",
    studentName: "Noah Williams",
    yearLevel: "Year 10",
    course: "ENG-10",
    assignment: "Essay: Identity Texts",
    score: 78,
    maxScore: 100,
    weight: "25%",
    submittedAt: "2026-07-08",
    scale: "numeric",
  },
  {
    id: "GRD-5",
    studentName: "Amelia Scott",
    yearLevel: "Year 5",
    course: "LIT-05",
    assignment: "Reading OTJ — Mid Term",
    score: 4,
    maxScore: 5,
    weight: "OTJ",
    submittedAt: "2026-07-07",
    scale: "otj",
  },
  {
    id: "GRD-6",
    studentName: "Tia Ngata",
    yearLevel: "Kindy",
    course: "ELC-K",
    assignment: "Learning story: Belonging",
    score: 5,
    maxScore: 5,
    weight: "Narrative",
    submittedAt: "2026-07-06",
    scale: "otj",
  },
];

export const invoices: Invoice[] = [
  {
    id: "INV-8841",
    studentName: "Maya Chen",
    yearLevel: "Year 11",
    description: "Term 2 2026 school fees — Installment 2",
    amount: 85000,
    dueDate: "2026-07-20",
    status: "pending",
  },
  {
    id: "INV-8830",
    studentName: "Jordan Blake",
    yearLevel: "Year 8",
    description: "Arts materials levy",
    amount: 6500,
    dueDate: "2026-07-05",
    status: "overdue",
  },
  {
    id: "INV-8822",
    studentName: "Aisha Rahman",
    yearLevel: "Year 13",
    description: "Senior exam & assessment fees",
    amount: 15000,
    dueDate: "2026-06-30",
    status: "paid",
  },
  {
    id: "INV-8850",
    studentName: "Leo Park",
    yearLevel: "Year 1",
    description: "Enrollment deposit",
    amount: 20000,
    dueDate: "2026-07-25",
    status: "draft",
  },
  {
    id: "INV-8811",
    studentName: "Tia Ngata",
    yearLevel: "Kindy",
    description: "Early learning term fees",
    amount: 35000,
    dueDate: "2026-07-20",
    status: "pending",
  },
];

export const leads: Lead[] = [
  {
    id: "LEAD-220",
    name: "Priya Nair",
    email: "priya.nair@email.com",
    source: "Open Day",
    stage: "tour",
    interest: "Primary Pathway",
    yearLevel: "Year 3",
    lastContact: "2026-07-12",
    score: 86,
  },
  {
    id: "LEAD-221",
    name: "Ethan Cole",
    email: "ethan.cole@email.com",
    source: "Website",
    stage: "application",
    interest: "Arts & Media",
    yearLevel: "Year 9",
    lastContact: "2026-07-11",
    score: 74,
  },
  {
    id: "LEAD-222",
    name: "Amara Okonkwo",
    email: "amara.o@email.com",
    source: "Referral",
    stage: "accepted",
    interest: "NCEA STEM",
    yearLevel: "Year 11",
    lastContact: "2026-07-10",
    score: 93,
  },
  {
    id: "LEAD-223",
    name: "Lucas Meyer",
    email: "lucas.meyer@email.com",
    source: "Social Ads",
    stage: "inquiry",
    interest: "Kindy / Early Learning",
    yearLevel: "Kindy",
    lastContact: "2026-07-13",
    score: 52,
  },
  {
    id: "LEAD-224",
    name: "Hannah Brooks",
    email: "hannah.b@email.com",
    source: "Counsellor Fair",
    stage: "enrolled",
    interest: "Year 13 Scholarship Prep",
    yearLevel: "Year 13",
    lastContact: "2026-07-08",
    score: 97,
  },
];

export const alumni: Alumni[] = [
  {
    id: "ALM-01",
    name: "Sofia Alvarez",
    graduationYear: 2023,
    program: "Business Pathway",
    employer: "ANZ Bank Vanuatu",
    location: "Port Vila, VU",
    engagement: "high",
    donated: 145000,
  },
  {
    id: "ALM-02",
    name: "Marcus Lee",
    graduationYear: 2021,
    program: "STEM / Digital Tech",
    employer: "Telecom Vanuatu",
    location: "Port Vila, VU",
    engagement: "medium",
    donated: 42000,
  },
  {
    id: "ALM-03",
    name: "Elena Voss",
    graduationYear: 2020,
    program: "Arts & Media",
    employer: "Vanuatu Daily Post",
    location: "Luganville, VU",
    engagement: "high",
    donated: 280000,
  },
  {
    id: "ALM-04",
    name: "David Kim",
    graduationYear: 2022,
    program: "Senior Excellence",
    employer: "SPC — Pacific Community",
    location: "Nouméa, NC",
    engagement: "low",
    donated: 0,
  },
];

export const liveSessions: LiveSession[] = [
  {
    id: "LIVE-1",
    title: "Biology Internal Catch-up",
    course: "BIO-11",
    yearLevels: ["Year 11", "Year 12"],
    host: "Dr. Elena Hale",
    startsAt: "2026-07-14T10:00:00",
    duration: "45 min",
    attendees: 22,
    status: "live",
  },
  {
    id: "LIVE-2",
    title: "Digital Tech Office Hours",
    course: "DIG-13",
    yearLevels: ["Year 12", "Year 13"],
    host: "Mr. Raj Singh",
    startsAt: "2026-07-14T15:30:00",
    duration: "60 min",
    attendees: 0,
    status: "upcoming",
  },
  {
    id: "LIVE-3",
    title: "Primary Literacy Shared Reading",
    course: "LIT-05",
    yearLevels: ["Year 4", "Year 5", "Year 6"],
    host: "Ms. Camila Ortiz",
    startsAt: "2026-07-13T11:00:00",
    duration: "40 min",
    attendees: 29,
    status: "ended",
  },
];

export const applications: EnrollmentApplication[] = [
  {
    id: "APP-771",
    applicant: "Priya Nair",
    program: "Primary Pathway",
    yearLevel: "Year 3",
    submittedAt: "2026-07-09",
    status: "interview",
    completeness: 92,
  },
  {
    id: "APP-772",
    applicant: "Ethan Cole",
    program: "Arts & Media",
    yearLevel: "Year 9",
    submittedAt: "2026-07-08",
    status: "documents",
    completeness: 68,
  },
  {
    id: "APP-773",
    applicant: "Amara Okonkwo",
    program: "NCEA STEM",
    yearLevel: "Year 11",
    submittedAt: "2026-07-05",
    status: "approved",
    completeness: 100,
  },
  {
    id: "APP-774",
    applicant: "Lucas Meyer",
    program: "Early Learning",
    yearLevel: "Kindy",
    submittedAt: "2026-07-12",
    status: "review",
    completeness: 45,
  },
  {
    id: "APP-775",
    applicant: "Riley Zhao",
    program: "NCEA STEM",
    yearLevel: "Year 10",
    submittedAt: "2026-07-11",
    status: "waitlist",
    completeness: 100,
  },
];

export const messages: Message[] = [
  {
    id: "MSG-01",
    subject: "Term 2 attendance reminder — Secondary",
    from: "Elena Hale",
    audience: "band",
    target: "Secondary",
    channel: "app",
    sentAt: "2026-07-13T08:00:00",
    opens: 412,
    status: "sent",
  },
  {
    id: "MSG-02",
    subject: "Kindy learning story published",
    from: "Camila Ortiz",
    audience: "year-level",
    target: "Kindy",
    channel: "portal",
    sentAt: "2026-07-12T16:20:00",
    opens: 38,
    status: "sent",
  },
  {
    id: "MSG-03",
    subject: "NCEA internal dates for Year 11–13",
    from: "Raj Singh",
    audience: "year-level",
    target: "Year 11–13",
    channel: "email",
    sentAt: "2026-07-14T09:00:00",
    opens: 0,
    status: "scheduled",
  },
  {
    id: "MSG-04",
    subject: "Family interview confirmation — Year 3",
    from: "Admissions",
    audience: "family",
    target: "Priya Nair family",
    channel: "sms",
    sentAt: "2026-07-11T11:15:00",
    opens: 1,
    status: "sent",
  },
  {
    id: "MSG-05",
    subject: "Whole-school sports carnival notice",
    from: "Elena Hale",
    audience: "all-school",
    target: "Kindy–Year 13",
    channel: "email",
    sentAt: "2026-07-10T14:00:00",
    opens: 980,
    status: "sent",
  },
];

export const integrations: Integration[] = [
  {
    id: "INT-01",
    name: "MoET Vanuatu student registry",
    category: "Government",
    description:
      "Keep Kindy–Year 13 records aligned with the Ministry of Education & Training.",
    status: "connected",
    lastSync: "2026-07-14 07:12",
  },
  {
    id: "INT-02",
    name: "Google Workspace for Education",
    category: "Productivity",
    description: "Roster sync for classroom drives, Meet rooms, and accounts.",
    status: "connected",
    lastSync: "2026-07-14 06:40",
  },
  {
    id: "INT-03",
    name: "Microsoft 365 Education",
    category: "Productivity",
    description: "SSO and Teams class channels for secondary cohorts.",
    status: "syncing",
    lastSync: "2026-07-14 08:05",
  },
  {
    id: "INT-04",
    name: "Vanuatu assessment results feed",
    category: "Assessment",
    description: "Import Year 11–13 assessment outcomes into the gradebook.",
    status: "connected",
    lastSync: "2026-07-13 21:18",
  },
  {
    id: "INT-05",
    name: "Vatu school fees gateway",
    category: "Finance",
    description:
      "Push VT invoices and reconcile family payments via local banking rails.",
    status: "available",
    lastSync: "—",
  },
  {
    id: "INT-06",
    name: "Library & ID card system",
    category: "Campus ops",
    description: "Link student IDs for attendance kiosks and borrowing.",
    status: "error",
    lastSync: "2026-07-12 19:02",
  },
];

export const dashboardStats = {
  activeStudents: 1154,
  pendingEnrollments: 47,
  attendanceToday: 96.4,
  outstandingBilling: 4850000,
  openLeads: 63,
  liveSessions: 4,
  avgGpa: 3.42,
  alumniEngaged: 312,
  yearSpan: "Kindy – Year 13",
  messagesSentWeek: 128,
};

export const activityFeed = [
  {
    id: 1,
    text: "Amara Okonkwo accepted offer for Year 11 NCEA STEM",
    time: "12 min ago",
    type: "crm",
  },
  {
    id: 2,
    text: "Auto-attendance synced for BIO-11 Year 11 (28/28)",
    time: "28 min ago",
    type: "attendance",
  },
  {
    id: 3,
    text: "Invoice INV-8830 marked overdue — Jordan Blake (Year 8)",
    time: "1 hr ago",
    type: "billing",
  },
  {
    id: 4,
    text: "Maya Chen submitted Biology IA 2.4 — scored Excellence",
    time: "2 hr ago",
    type: "gradebook",
  },
  {
    id: 5,
    text: "Kindy learning stories published to 22 families",
    time: "3 hr ago",
    type: "communications",
  },
  {
    id: 6,
    text: "Assessment results feed synced for Year 12–13 standards",
    time: "4 hr ago",
    type: "integrations",
  },
  {
    id: 7,
    text: "Library marked Digital Citizenship overdue — Noah Williams",
    time: "5 hr ago",
    type: "library",
  },
  {
    id: 8,
    text: "Year 11 peer review circle gained 14 new replies",
    time: "6 hr ago",
    type: "social",
  },
];

export const socialPosts: SocialPost[] = [
  {
    id: "SOC-01",
    title: "Year 11 peer review circle — Biology IA drafts",
    author: "Maya Chen",
    yearLevel: "Year 11",
    type: "peer-review",
    space: "NCEA Biology Hub",
    replies: 14,
    likes: 28,
    updatedAt: "2026-07-14T09:20:00",
  },
  {
    id: "SOC-02",
    title: "Kindy whānau sharing wall — Belonging stories",
    author: "Camila Ortiz",
    yearLevel: "Kindy",
    type: "discussion",
    space: "Early Learning Community",
    replies: 22,
    likes: 41,
    updatedAt: "2026-07-13T16:05:00",
  },
  {
    id: "SOC-03",
    title: "Intermediate science fair project teams",
    author: "Jordan Blake",
    yearLevel: "Year 8",
    type: "project",
    space: "STEM Makers",
    replies: 9,
    likes: 17,
    updatedAt: "2026-07-13T11:40:00",
  },
  {
    id: "SOC-04",
    title: "Year 13 scholarship study buddies",
    author: "Aisha Rahman",
    yearLevel: "Year 13",
    type: "club",
    space: "Senior Mentors",
    replies: 11,
    likes: 33,
    updatedAt: "2026-07-12T18:10:00",
  },
  {
    id: "SOC-05",
    title: "Primary reading buddies signup (Y5–Y6)",
    author: "Amelia Scott",
    yearLevel: "Year 5",
    type: "club",
    space: "Literacy Circles",
    replies: 18,
    likes: 25,
    updatedAt: "2026-07-12T10:00:00",
  },
];

export const libraryItems: LibraryItem[] = [
  {
    id: "LIB-2201",
    title: "The Arrival",
    author: "Shaun Tan",
    category: "Fiction",
    yearLevels: ["Year 5", "Year 6", "Year 7", "Year 8"],
    status: "on-loan",
    borrower: "Jordan Blake",
    dueDate: "2026-07-21",
  },
  {
    id: "LIB-1180",
    title: "NCEA Biology Study Guide",
    author: "ESA Publications",
    category: "Reference",
    yearLevels: ["Year 11", "Year 12"],
    status: "available",
    borrower: "—",
    dueDate: "—",
  },
  {
    id: "LIB-0442",
    title: "Counting Kindy: Number Play Pack",
    author: "Harbour Library",
    category: "Early learning kit",
    yearLevels: ["Kindy", "Year 1"],
    status: "reserved",
    borrower: "Kindy-A",
    dueDate: "2026-07-15",
  },
  {
    id: "LIB-3012",
    title: "Digital Citizenship for Teens",
    author: "Common Sense Ed.",
    category: "Non-fiction",
    yearLevels: ["Year 9", "Year 10", "Year 11"],
    status: "overdue",
    borrower: "Noah Williams",
    dueDate: "2026-07-08",
  },
  {
    id: "LIB-1777",
    title: "Te Ao Māori Story Collection",
    author: "Various",
    category: "Fiction",
    yearLevels: ["Year 2", "Year 3", "Year 4"],
    status: "available",
    borrower: "—",
    dueDate: "—",
  },
  {
    id: "LIB-4090",
    title: "Scholarship Calculus Workbook",
    author: "ESA Publications",
    category: "Reference",
    yearLevels: ["Year 13"],
    status: "on-loan",
    borrower: "Aisha Rahman",
    dueDate: "2026-07-25",
  },
];

export const healthRecords: HealthRecord[] = [
  {
    id: "HLT-01",
    studentName: "Maya Chen",
    yearLevel: "Year 11",
    type: "allergy",
    summary: "Mild peanut allergy — EpiPen stored at sick bay",
    recordedBy: "Nurse Patel",
    recordedAt: "2026-02-10",
    severity: "high",
    privateNote: true,
  },
  {
    id: "HLT-02",
    studentName: "Tia Ngata",
    yearLevel: "Kindy",
    type: "immunization",
    summary: "Immunisation schedule up to date for age",
    recordedBy: "Nurse Patel",
    recordedAt: "2026-03-01",
    severity: "info",
    privateNote: true,
  },
  {
    id: "HLT-03",
    studentName: "Jordan Blake",
    yearLevel: "Year 8",
    type: "visit",
    summary: "Sick bay visit — headache; returned to class after rest",
    recordedBy: "Nurse Patel",
    recordedAt: "2026-07-11",
    severity: "low",
    privateNote: false,
  },
  {
    id: "HLT-04",
    studentName: "Noah Williams",
    yearLevel: "Year 10",
    type: "medication",
    summary: "Inhaler for exercise-induced asthma — self-administer",
    recordedBy: "Nurse Patel",
    recordedAt: "2026-01-20",
    severity: "medium",
    privateNote: true,
  },
  {
    id: "HLT-05",
    studentName: "Amelia Scott",
    yearLevel: "Year 5",
    type: "plan",
    summary: "Individual health plan for seasonal hay fever",
    recordedBy: "Nurse Patel",
    recordedAt: "2026-04-15",
    severity: "medium",
    privateNote: true,
  },
  {
    id: "HLT-06",
    studentName: "Leo Park",
    yearLevel: "Year 1",
    type: "immunization",
    summary: "Awaiting Year 1 booster documentation from family",
    recordedBy: "Admin Office",
    recordedAt: "2026-07-01",
    severity: "info",
    privateNote: true,
  },
];

export const classSchedule: ClassPeriod[] = [
  {
    id: "SCH-01",
    day: "Monday",
    period: "P1",
    startTime: "08:45",
    endTime: "09:40",
    course: "ELC-K Discovery Play",
    teacher: "Ms. Ortiz",
    room: "Kindy A",
    yearLevels: ["Kindy"],
    band: "Early Childhood",
  },
  {
    id: "SCH-02",
    day: "Monday",
    period: "P1",
    startTime: "08:45",
    endTime: "09:40",
    course: "LIT-05 Literacy Circles",
    teacher: "Ms. Ortiz",
    room: "P5-B",
    yearLevels: ["Year 5"],
    band: "Primary",
  },
  {
    id: "SCH-03",
    day: "Monday",
    period: "P2",
    startTime: "09:45",
    endTime: "10:40",
    course: "SCI-08 Science Lab",
    teacher: "Mr. Singh",
    room: "Lab 2",
    yearLevels: ["Year 7", "Year 8"],
    band: "Intermediate",
  },
  {
    id: "SCH-04",
    day: "Monday",
    period: "P3",
    startTime: "11:00",
    endTime: "11:55",
    course: "BIO-11 NCEA Biology",
    teacher: "Dr. Hale",
    room: "S204",
    yearLevels: ["Year 11", "Year 12"],
    band: "Secondary",
  },
  {
    id: "SCH-05",
    day: "Tuesday",
    period: "P2",
    startTime: "09:45",
    endTime: "10:40",
    course: "ENG-10 World Texts",
    teacher: "Ms. Ortiz",
    room: "S110",
    yearLevels: ["Year 10"],
    band: "Secondary",
  },
  {
    id: "SCH-06",
    day: "Wednesday",
    period: "P4",
    startTime: "12:40",
    endTime: "13:35",
    course: "DIG-13 Digital Technologies",
    teacher: "Mr. Singh",
    room: "ICT Suite",
    yearLevels: ["Year 12", "Year 13"],
    band: "Secondary",
  },
  {
    id: "SCH-07",
    day: "Thursday",
    period: "P1",
    startTime: "08:45",
    endTime: "09:40",
    course: "Junior Primary Hub",
    teacher: "Mr. Singh",
    room: "P1",
    yearLevels: ["Year 1"],
    band: "Primary",
  },
  {
    id: "SCH-08",
    day: "Friday",
    period: "P3",
    startTime: "11:00",
    endTime: "11:55",
    course: "Senior Mentoring / Study",
    teacher: "Dr. Hale",
    room: "Library",
    yearLevels: ["Year 13"],
    band: "Secondary",
  },
];

export const reportHighlights = [
  {
    label: "Enrollment conversion",
    value: "34%",
    delta: "+4.2%",
    positive: true,
  },
  {
    label: "Average daily attendance",
    value: "95.8%",
    delta: "+1.1%",
    positive: true,
  },
  {
    label: "School fee collection rate",
    value: "91%",
    delta: "-2.3%",
    positive: false,
  },
  {
    label: "Class completion (online)",
    value: "88%",
    delta: "+6.0%",
    positive: true,
  },
  {
    label: "Family message open rate",
    value: "76%",
    delta: "+5%",
    positive: true,
  },
  {
    label: "CRM response time",
    value: "4.2h",
    delta: "-1.5h",
    positive: true,
  },
];
